[package]
name = "neurons"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
camino = "1.1.7"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_repr = "0.1.19"
